### ISSUE TITLE
Remove "jquery." from jsfiddle demo

### ISSUE THREAD

**Issue by alexgann** [CalvinSlusarski/Knockout-handsontable#8]
Thanks for the binding!  jsfiddle still referenecs jquery.handsontable which doesn't exist anymore.  May want to update your fiddle to avoid headscratching: http://jsfiddle.net/x3ejL/98/

Thanks again!

**Comment by CalvinSlusarski** [comment]
I'll take a look at it. Thanks

**Comment by CalvinSlusarski** [comment]
fixed.
