### ISSUE TITLE
passing index numbers as parameter to prepareColumnOptions function

### ISSUE THREAD

**Issue by psaliente** [CalvinSlusarski/Knockout-handsontable#9]
Hi
I have a case where I may need to pass the index of an array for the column option and I suppose that the function prepareColumnOptions expects a property of an object instead of an index. So on such an situation, my work around have been to bypass the prepareColumnOptions function call and directly passing columns to the options on handsontable.
will such a case be supported on the next version of your script?

thank you,

**Comment by CalvinSlusarski** [comment]
This issue should be resolved by my latest update. Let know if it is not.
